baseURL = 'https://victor-explore.github.io/'
languageCode = 'en-us'
title = 'Victor'
theme = 'PaperMod'

[params]
  math = true

  [params.profileMode]
    enabled = true
    title = "Victor"
    subtitle = "I talk about AI"
    subtitle2 = "And share insights about technology, society, and personal growth"
    imageUrl = "https://pbs.twimg.com/profile_images/1794626761671770112/UhwIrobb_400x400.png"
    imageTitle = "Profile Picture"
    imageWidth = 120 # custom size
    imageHeight = 120 # custom size

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/victor_explore"
  [[params.socialIcons]] # optional
    name = "github"
    url = "https://github.com/victor-explore"

  [params.social]
    facebook_admin = "" # If you have a Facebook admin ID
    twitter = "victor_explore" # Your Twitter handle without @

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
