baseURL = 'https://addyb0t.github.io/'
languageCode = 'en-us'
title = 'Addy'
theme = 'PaperMod'

[params]
  math = true
  ShowPageNavigation = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = false
  ShowPostNavLinks = true
  enableEmoji = true
  showtoc = true
  hideMeta = false
  mainSections = ["posts"]
  enableDropdownMenu = true

  [params.profileMode]
    enabled = true
    title = "Addy"
    subtitle = "Learning How Machines Learn"
    subtitle2 = "And share insights about technology, society, and personal growth"
    imageUrl = "/images/profile.jpg"
    imageTitle = "Profile Picture"
    imageWidth = 120 # custom size
    imageHeight = 120 # custom size

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/aadi29494"
  [[params.socialIcons]] # optional
    name = "github"
    url = "https://github.com/AddyB0t"

  [params.social]
    facebook_admin = "" # If you have a Facebook admin ID
    twitter = "aadi29494" # Your Twitter handle without @

  [params.assets]
    favicon = "/images/profile.jpg"
    favicon16x16 = "/images/profile.jpg"
    favicon32x32 = "/images/profile.jpg"
    apple_touch_icon = "/images/profile.jpg"

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "📄 CV"
    url = "/cv/"
    weight = 25
  [[menu.main]]
    identifier = "discord-community"
    name = "💬 Discord Community"
    url = "https://discord.com/invite/QHAbprqQme"
    weight = 30
    params = { newTab = true }
  [[menu.main]]
    identifier = "posts"
    name = "📝 Posts"
    url = "/posts/"
    weight = 35

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
